//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeSpoken.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commission
    {
        public int CommissionId { get; set; }
        public int QtrId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> SalesPersonId { get; set; }
        public Nullable<int> Qtr { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Qtr Qtr1 { get; set; }
        public virtual SalesPerson SalesPerson { get; set; }
    }
}
